version: '3.2'
services:
  development-svelte:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: Svelte-App
    stdin_open: true
    tty: true
